### ISSUE TITLE
Broken multimedia for version 23.7.1.1215

### ISSUE THREAD

**Issue by borodin-devel** [flathub/ru.yandex.Browser#17]
I post it here cause official QA support from Yandex said that they don't support Flatpak.

Update from 23.5.4.685 to 23.7.1.1215 broke multimedia on most sites like Youtube, even voice of Google Translate is broken. Browser tries to reload the page several time and end up on error page. No error logs in browser://crashes/. Had to fallback in order to work.
Seems like some codec/hardware acceleration problem to me. Host machine is Debian 12.

```
Commit: 79447ca51e94e4d6e0bf7d5195b31eb5b034ec78b793d04f6c300c260c974d1f <- still broken (why version is not updated?)
Parent: 1c541c57f053c6407247a1fc04dbdd495bd69fe002b11421f19aa7405b2becdc
Subject: Update yandex-browser.rpm to 23.7.1.1215 (e888dada)
Date: 2023-08-03 08:34:50 +0000
History: 

Commit: 1c541c57f053c6407247a1fc04dbdd495bd69fe002b11421f19aa7405b2becdc <- broken
Subject: Update yandex-browser.rpm to 23.7.1.1215 (dc3d301d)
Date: 2023-08-01 13:13:05 +0000

Commit: 4abd854b41cb7740fdbaf1ee8f43618d8305014cb17e625e57bef2c1e8138802 <- works
Subject: Update yandex-browser.rpm to 23.5.4.685 (ae3f46d0)
 Date: 2023-07-05 11:35:21 +0000
```

**Comment by Rootovich** [comment]
same problem on steam deck

**Comment by fat0troll** [comment]
Looks like I need to update codecs bundled with browser. Will test the fix and release new version.
