### ISSUE TITLE
Браузер не запускается в Wayland

### ISSUE THREAD

**Issue by feschukov** [flathub/ru.yandex.Browser#19]
Вроде как Яндекс починили работу браузера в Wayland, хотелось бы это проверить, но не удаётся запустить браузер с поддержкой Wayland. Тестирую на Fedora Silverblue 38, версия браузера 23.7.1.1215 (64-bit), версия служб Flatpak 1.15.4.

Лог терминала:
```
$ flatpak run ru.yandex.Browser --ozone-platform-hint=auto
Gtk-Message: 19:35:53.686: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:35:53.688: Failed to load module "canberra-gtk-module"
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[2:2:0827/193554.014944:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
[2:2:0827/193554.018155:ERROR:brand_package_util.cc(110)] Failed to verify partner_config signature, config will be ignored
[2:2:0827/193554.109579:ERROR:wayland_connection.cc(194)] Failed to connect to Wayland display: Нет такого файла или каталога (2)
[2:2:0827/193554.109636:ERROR:ozone_platform_wayland.cc(234)] Failed to initialize Wayland platform
[2:2:0827/193554.109648:ERROR:env.cc(255)] The platform failed to initialize.  Exiting. 
```

**Comment by feschukov** [comment]
Проверил из другой системы работу браузера в Wayland, установленного из deb-пакета. И пользоваться им пока нельзя, вылетает при вызове меню приложения. Из всех проблем поправили только вызов контекстного меню. Непонятно куда разработчики браузера Яндекс смотрят вообще. Да и судя по ответу тех. поддержки, им до фонаря поддержка Wayland и тем более самодостаточные пакеты.

**Comment by feschukov** [comment]
Проверил работу браузера из тестовой сборки. Всё работает корректно, по умолчанию запускается в X11. Через параметр `--ozone-platform-hint=auto` запускается окно в Wayland.

**Comment by fat0troll** [comment]
Сейчас можно попробовать дать права на запуск браузера в Wayland через Flatseal (по умолчанию права на сокет Wayland я отключил, так как браузер раньше толком в этом состоянии не работал у меня). Если на стороне Яндекса действительно починили поддержку Wayland, я могу включить доступ к сокету Wayland по умолчанию.

**Comment by feschukov** [comment]
> 

Он крашится ещё на Wayland. Браузер сам по умолчанию открывается на иксах. Я отправил PR, в котором просто дал возможность запускать браузер в Wayland принудительно. Сейчас если включить Wayland через flags, то после браузер вообще не запустить никак, только через терминал с аргументом отключения всех флагов. Поэтому доступ к Wayland в любом случае нужен, просто пока не убирать fallback-x11.
