### ISSUE TITLE
Кривой пакет (иконки, перемещение окон, скейлинг)

### ISSUE THREAD

**Issue by pztrn** [flathub/ru.yandex.Browser#25]
На основе сравнения с установленной в систему версией в Arch, KDE, Wayland, полное обновление сделано 30 минут назад:

1. Стандартная иконка от xwayland вместо иконки приложения после запуска. С установленной в систему версией такой проблемы нет.
2. Не подтягиваются параметры скейлинга. С установленной в систему версией все ОК, также все ОК с Chromium и Microsoft Edge из flatpak.
3. Невозможно переместить окно. При попытке перемещения оного браузер крошится, причем только GUI часть, flatpak ругается про фоновую активность и приходится делать `flatpak kill ru.yandex.Browser`, чтобы полностью перезапустить браузер. С установленной в систему версией, а также с Chromium и Microsoft Edge из flatpak таких проблем нет.

**Comment by fat0troll** [comment]
Нужно больше репортов по поводу работы Яндекс.Браузера в Wayland. У меня такое ощущение, что под гномом оно работает, а под кедами — нет.

**Comment by pztrn** [comment]
Про п.3 - все верно, убрал разрешение вяленого, все стало работать нормально (ну, относительно). Также начали подтягиваться начали настройки скейлинга, показывается верная иконка в панели задач.

Однако остались падения спустя <10 секунд после запуска.
