### ISSUE TITLE
Yandex Browser + CryptoPro

### ISSUE THREAD

**Issue by zhenyakoltsov** [flathub/ru.yandex.Browser#29]
How to make this version work together with CryptoPro?

**Comment by fat0troll** [comment]
This is not possible at the time. Support for the CryptoPro in Flatpak version of Yandex Browser will be added in a future update, when I'd figure how to make it work (or someone send me a patch with working configuration).

**Comment by zhenyakoltsov** [comment]
По данному вопросу не нашлось решения?

**Comment by fat0troll** [comment]
По поводу КриптоПро.

Распространение дистрибутива КриптоПро является деятельностью, лицензируемой ФСБ России. Ни у меня, ни у тем более у Флатхаба, такой лицензии нет. Пока не появится возможность использовать нативные плагины через freedesktop-протокол (и пока поддержка такого протокола не появится у самого КриптоПро), способов получить рабочий КриптоПро во флатпак-версии Яндекс-браузера я не вижу.

Таким образом, в этом пакете поддержки КриптоПро не появится примерно никогда. Возможно, в будущем, если/когда Яндекс подхватит работу над пакетом тут (или даст мне необходимые лицензионные права делать это от их имени), эта ситуация изменится.

**Comment by fat0troll** [comment]
@hard-coder обрати внимание на этот старый тикет, пожалуйста. Люди хотят использовать КриптоПРО, а у меня ни технической, ни лицензионной возможности организовать это не было. У тебя такая возможность, думаю, есть, и ты можешь порадовать пользователей фичей, для которой многие и используют Яндекс-браузер под линуксом.

**Comment by zhenyakoltsov** [comment]
Прошу осуществить данную возможность в браузере
