### ISSUE TITLE
Some new features are not working

### ISSUE THREAD

**Issue by avsprv** [flathub/ru.yandex.Browser#36]
After installing this version, I noticed that compared to the official version, there are no such functions as "retelling the video", "help with the text"..

What could this be related to? Is it possible to manually enable these functions?

**Comment by fat0troll** [comment]
This (https://github.com/flathub/ru.yandex.Browser/pull/37/files#diff-5f23be9490bebe82c1a55e2da3290383b28298e358c8deb5236a209e9d95f1a2R15) is an actual fix for this. Update will be released on Flathub soon, and you can set this env variable in your installation now, if you're not want to wait more.

The only question I have now is WHY Yandex did exactly this.
