### ISSUE TITLE
A drop in productivity

### ISSUE THREAD

**Issue by dblackCat** [flathub/ru.yandex.Browser#45]
A drop in productivity. My current version. 24.1.5.794

I noticed it a long time ago, but now it began to bother me. Strong brakes in the October CMS admin panel. I suspect this is because of Laravel Turbo, as it generates a lot of queries.

There are also problems when using any frontend frameworks. For example alpine.js .

It is expressed in poor responsiveness. For example, we click on the button, and the action takes place with a delay.

At the same time, Gnome does not understand what is happening and displays a window that the application is not responding.

![Снимок экрана от 2024-07-01 10-44-38](https://github.com/flathub/ru.yandex.Browser/assets/43875915/c5f251a5-8fdd-4ec6-9787-34711546a21b)

**Comment by fat0troll** [comment]
I think that this issue must be filled in the upstream. Flatpak build doesn't modify browser in any way, so there is nothing that should prevent browser to work in full speed.

You may try official DEB/RPM package for Yandex Browser and then report issue to Yandex directly.
