### ISSUE TITLE
Проблема при загрузке страниц

### ISSUE THREAD

**Issue by zhenyakoltsov** [flathub/ru.yandex.Browser#48]
После обновления браузера до версии 24.4.1.951 перестали открываться многие страницы.
![sportmaster](https://github.com/flathub/ru.yandex.Browser/assets/150870944/20619632-ff0f-4e4d-a9ff-9a46b2d0828d)
![yandex](https://github.com/flathub/ru.yandex.Browser/assets/150870944/5086d986-e975-4a1a-a101-c52c79b9c07e)

**Comment by Rootovich** [comment]
Опять старая проблема годичной давности. Все сайты видео контентом перестали открываться

**Comment by rd1bcy** [comment]
> Опять старая проблема годичной давности. Все сайты видео контентом перестали открываться

а как это поправили в итоге?

**Comment by fat0troll** [comment]
Кодекам опять плохо, после мержа #47 всё заработает.

**Comment by rd1bcy** [comment]
> Кодекам опять плохо, после мержа #47 всё заработает.
спасибо большое, ютуб и вкплей заработали
но падает вкладка озона с заказами
![image](https://github.com/flathub/ru.yandex.Browser/assets/169486694/03fd1d4c-ab31-4e94-9df5-ec74d24ad718)

**Comment by rd1bcy** [comment]
еще вк видео не работает((

**Comment by zhenyakoltsov** [comment]
Обновился до версии 24.6.1.852, стало работать лучше но все равно падают страницы.

**Comment by Rootovich** [comment]
> еще вк видео не работает
Подтверждаю. проблема есть
