### ISSUE TITLE
getting system's dark mode status

### ISSUE THREAD

**Issue by ShohruxYusupov** [flathub/ru.yandex.Browser#8]
seems like Y.browser can't detect that dark mode is globally enabled. 
my case:
- runned browser;
- switched dark mode on
- going to ya.ru, you.com (or runned extensions) 
- result: sites are still in day mode.

OS: fedora 38, all packages are updated.

**Comment by fat0troll** [comment]
is browser user interface becomes dark, or only sites stay in light mode?

**Comment by ShohruxYusupov** [comment]
both of them stay in light mode, while on OS dark mode is enabled:

![image](https://github.com/flathub/ru.yandex.Browser/assets/36853429/7f426d26-bc61-4a11-8c5e-58f1e70db68e)

**Comment by fat0troll** [comment]
Will look into it, thanks!

**Comment by fat0troll** [comment]
At the time I found no solutions for automatic honoring of dark mode for Chrome-based browsers in Flatpak. 

You can mitigate this by creating file `~/.var/app/ru.yandex.Browser/config/yandex_browser-flags.conf` with the following contents:

```
--force-dark-mode
--use-features=WebUIDarkMode
```

Hope in future there will be streamlined solution for theming/honoring dark more in Chrome-based flatpaks.
